# Generated by Django 3.1.4 on 2021-01-05 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_auto_20210105_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='posts_liked_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
