# Generated by Django 3.1.4 on 2021-01-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_author'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(check=models.Q(likes__gte='0'), name='likes_non_negative'),
        ),
    ]
