# Generated by Django 3.1.4 on 2021-01-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('identifier', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='<django.db.models.fields.textfield>')),
            ],
        ),
    ]
