# Generated by Django 3.1.4 on 2021-01-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210102_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
