# Generated by Django 3.1.4 on 2021-01-02 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room_anonymous'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('name', 'anonymous')},
        ),
    ]
