# Generated by Django 3.1.4 on 2021-01-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20210102_2050'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='room',
            name='unique name in its anonymity type',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='identifier',
            new_name='id',
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('id', 'anonymous'), name='composite primary key'),
        ),
    ]
