# Generated by Django 3.1.4 on 2021-01-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20210102_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='url',
            field=models.TextField(default='gen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
