# Generated by Django 3.1.4 on 2021-01-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default='This guy likes being soo mysterious...', max_length=200),
        ),
    ]
